services:
  gg-test-node-backend-1:
    build:
      context: .
      target: production
    image: gg-test-node-backend-1
    container_name: gg-test-node-backend-1
    depends_on:
      - gg-test-node-backend-1-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: gg-test-node-backend-1-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  gg-test-node-backend-1-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: gg-test-node-backend-1
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
